name: Build and Create release

on: 
  [push]

env:
  BUILD_TYPE: RELEASE

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

      # On Windows machines ${{runner.workspace}} is a folder that has the name of the repository, 
      # but the checkout action checks the code out to a nested directory with te same name.
    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Install conan
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install conan
    
    - name: Configure and build
      run: pwsh -command "./build.ps1 ${env:BUILD_TYPE}"